name: build

on:
  push:
    branches:
      - feature/*
      - bugfix/*
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7
      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
