name: create release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: get tag
        run: echo "VTAG=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
      - name: get version tag
        run: echo "VERSION=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV
      - name: Restore Dependencies
        run: dotnet restore
      - name: build
        run: dotnet build -c Release --no-restore
      - name: publish Windows version
        run: dotnet publish -c Release -o ./publish -r win-x64 -p:Version="${{env.VERSION}}" -p:PublishSingleFile=true --self-contained
      - name: rename Windows executable
        run: mv ./publish/CharacterDataEditor.exe ./publish/Knockout-Arcade-Character-Editor-Windows-x64.exe
      - name: remove debug artifacts
        run: rm ./publish/*.pdb -fr
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: publish_artifacts
          path: ./publish
      - name: zip publish artifacts
        uses: vimtor/action-zip@v1
        with: 
          files: ./publish
          dest: Character-Data-Editor-Windows-x64.zip
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          body_path: .github/workflows/ReleaseNotes.md
          files: Character-Data-Editor-Windows-x64.zip